config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_scope :user do
    unauthenticated :user do
      root to: 'devise/sessions#splash', as: :unauthenticated_root
    end

    authenticated :user do
      root to: 'groups#index', as: :authenticated_root
    end
  end

  resources :groups do
    resources :entities do
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :entities
  validates :name, presence: true
  has_one_attached :icon
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entities, foreign_key: :author_id
  has_many :groups, foreign_key: :author_id
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password)
    end
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def new
    @entity = Entity.new
    @groups = current_user.groups
    @group = current_user.groups.find(params[:group_id])
  end

  def create
    entity = Entity.create(entity_params)
    entity.author = current_user
    group = current_user.groups.find(params[:group_id])

    if entity.save
      entity.groups << Group.find(params[:entity][:group_ids]) if params[:entity][:group_ids].present?

      redirect_to group_path(group)
      flash[:notice] = 'Entity created successfully'
    else
      redirect_to new_entity_path
      flash[:alert] = entity.errors.full_messages.join(', ')
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def show
    @group = Group.find_by(id: params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    group = Group.create(group_params)
    group.author = current_user

    if group.save
      redirect_to group_path(group)
      flash[:notice] = 'Group created successfully'
    else
      redirect_to new_group_path
      flash[:alert] = group.errors.full_messages.join(', ')
    end
  end

  def edit
    @group = Group.find_by(id: params[:id])
  end

  def update
    group = Group.find_by(id: params[:id])
    group.update(group_params)
    redirect_to group_path(group)
  end

  def destroy
    Group.destroy(params[:id])
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/new.html.erb
<div class="new-group flex flex-col items-center gap-2 min-h-screen">
  <div
    class="
      nav
      flex
      justify-center
      items-center
      bg-[#3778c2]
      py-2
      w-full
      sticky
      z-10
      top-0
    "
  >
    <h2 class="text-2xl text-gray-100">ADD NEW ENTITY</h2>
    <div class="actions absolute left-3">
      <%= link_to "Back", group_path(@group), class: "text-gray-100" %>
    </div>
  </div>

  <%= form_with model: @entity, class: "flex flex-col gap-2 w-full px-2", url: group_entities_path(@group) do |form| %>
    <div class="field w-full">
      <%= form.text_field :name, placeholder: "Name", class: "form-control w-full" %>
    </div>

    <div class="field amount w-full">
      <%= form.number_field :amount, placeholder: "Amount", class: "form-control w-full" %>
    </div>

    <div class="field groups w-full">
      <%= form.label :group_ids,
                 "Select categories to add this transaction to. Press CTRL+click or click and drag to select multiple",
                 class: "form-label" %>
      <%= select_tag "entity[group_ids][]",
      options_from_collection_for_select(@groups, :id, :name, selected: @group.id),
      { multiple: true, class: "form-control w-full [&>*]:p-2", size: @groups.count } %>
    </div>

    <div class="actions w-full bg-[#3778c2] text-white p-2 text-center">
      <%= form.submit class: "w-full hover:cursor-pointer" %>
    </div>
  <% end %>

</div>

app/views/groups/_group.html.erb
<div class="group flex items-center relative w-full bg-white">
  <div class="icon h-[120px] object-contain aspect-1 flex items-center p-2">
    <%= image_tag group.icon %>
  </div>
  <div class="group-info">
    <div class="group-name text-xl">
      <%= link_to group.name, group_path(group) %>
    </div>
    <div class="group-amount absolute right-2 bottom-2">
      <%= number_to_currency(group.entities.sum(:amount)) %>
    </div>
  </div>
</div>

app/views/groups/_transaction.html.erb
<div
  class="
    transaction
    flex
    justify-between
    items-center
    gap-x-20
    relative
    w-full
    bg-white
    h-[120px]
    p-2
  "
>
  <div class="transaction-name text-xl">
    <%= entity.name %>
  </div>
  <div class="transaction-amount">
    <p class="entity-amount"><%= number_to_currency(entity.amount) %></p>
    <p class="entity-created-time absolute right-2 bottom-2 text-xs"><%= entity.created_at.strftime("%B%e, %Y%l:%M %p") %>
    </p>
  </div>
</div>

app/views/groups/index.html.erb
<div class="groups flex flex-col items-center gap-2 bg-gray-300 min-h-screen">
  <div
    class="
      nav
      flex
      justify-center
      items-center
      bg-[#3778c2]
      py-2
      w-full
      sticky
      z-10
      top-0
    "
  >
    <h2 class="text-2xl text-gray-100">CATEGORIES</h2>
    <div class="new absolute right-3">
      <%= link_to "New", new_group_path, class: "text-gray-100" %>
    </div>
  </div>
  <div class="px-2 w-full flex flex-col gap-2 mb-2">
    <%= render partial: "group", collection: @groups, as: :group %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="new-group flex flex-col items-center gap-2 min-h-screen">
  <div
    class="
      nav
      flex
      justify-center
      items-center
      bg-[#3778c2]
      py-2
      w-full
      sticky
      z-10
      top-0
    "
  >
    <h2 class="text-2xl text-gray-100">ADD NEW GROUP</h2>
    <div class="actions absolute left-3">
      <a href="/" class="text-white cursor-pointer">Back</a>
    </div>
  </div>

  <%= form_with(model: @group, html: { class: "flex flex-col w-full gap-2 px-2" }) do |form| %>
    <div class="field w-full">
      <%= form.text_field :name, placeholder: "Name", class: "form-control w-full" %>
    </div>

    <div class="field file-upload w-full">
      <%= form.file_field :icon,
                      accept: "image/png, image/jpeg, image/jpg",
                      class: "form-control w-full" %>
    </div>

    <div class="actions w-full bg-[#3778c2] text-white p-2 text-center">
      <%= form.submit class: "w-full hover:cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<div
  class="groups-show flex flex-col items-center gap-2 bg-gray-300 min-h-screen"
>
  <div
    class="
      nav
      flex
      justify-center
      items-center
      bg-[#3778c2]
      py-2
      w-full
      sticky
      z-10
      top-0
    "
  >
    <h2 class="text-2xl text-gray-100"><%= @group.name %></h2>
    <div class="actions absolute right-3 text-white text-sm">
      <%= number_to_currency(@group.entities.sum(:amount)) %>
    </div>
    <div class="actions absolute left-3">
      <a href="/" class="text-white cursor-pointer">Back</a>
    </div>
  </div>
  <div class="px-2 w-full flex flex-col gap-2 mb-2">
    <%= render partial: "transaction",
    collection: @group.entities.order(created_at: :desc),
    as: :entity %>
  </div>
  <%= button_to "Add Transaction",
  new_group_entity_path(@group),
  method: :get,
  class: "bg-[#3778c2] text-white py-2 px-4 rounded mb-4 w-full" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>

      <% if notice %>
        <p
          class="
            flash
            notice
            p-2.5
            my-2.5
            rounded
            bg-[#d9edf7]
            text-[#31708f]
            text-center
            absolute
            bottom-0
            z-20
            w-full
          "
        ><%= notice %></p>
      <% end %>

      <% if alert %>
        <p
          class="
            flash
            alert
            p-2.5
            my-2.5
            rounded
            bg-[#f2dede]
            text-[#a94442]
            text-center
            absolute
            bottom-0
            z-20
            w-full
          "
        ><%= alert %></p>
      <% end %>

      <% if flash[:error] %>
        <p
          class="
            flash
            error
            p-2.5
            my-2.5
            rounded
            bg-[#f2dede]
            text-[#a94442]
            text-center
            absolute
            bottom-0
            z-20
            w-full
          "
        ><%= flash[:error] %></p>
      <% end %>
    </main>
  </body>
</html>